# Generated by Django 4.2.2 on 2025-07-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Booking1',
        ),
    ]
