# Generated by Django 4.2.2 on 2025-07-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_booking_booking1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking1',
        ),
    ]
