# Generated by Django 4.2.2 on 2025-07-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_good_warehouse_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='user_type',
            field=models.CharField(choices=[('provider', 'Поставщик'), ('consumer', 'Потребитель')], default='provider', max_length=10),
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
